import type { Migration } from "./Migration";

const sql = `
	CREATE TABLE IF NOT EXISTS items (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		origin TEXT NOT NULL,
		type TEXT NOT NULL DEFAULT 'story',
		name TEXT NOT NULL,
		description TEXT,
		acceptance_criteria TEXT NOT NULL DEFAULT '[]',
		status TEXT NOT NULL DEFAULT 'todo',
		current_phase INTEGER,
		starred BOOLEAN NOT NULL DEFAULT false,
		jira_key TEXT
	);

	-- Backfill the column on databases created before it was introduced.
	ALTER TABLE items ADD COLUMN IF NOT EXISTS starred BOOLEAN NOT NULL DEFAULT false;
	ALTER TABLE items ADD COLUMN IF NOT EXISTS jira_key TEXT;

	CREATE INDEX IF NOT EXISTS items_origin_idx ON items (origin);

	CREATE TABLE IF NOT EXISTS comments (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
		idx INTEGER NOT NULL,
		text TEXT NOT NULL,
		phase INTEGER,
		timestamp TEXT NOT NULL,
		type TEXT NOT NULL DEFAULT 'comment'
	);

	CREATE TABLE IF NOT EXISTS links (
		item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
		type TEXT NOT NULL,
		target_id INTEGER NOT NULL,
		PRIMARY KEY (item_id, type, target_id)
	);

	CREATE TABLE IF NOT EXISTS plan_phases (
		item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
		idx INTEGER NOT NULL,
		name TEXT NOT NULL,
		manual_checks TEXT,
		PRIMARY KEY (item_id, idx)
	);

	CREATE TABLE IF NOT EXISTS plan_tasks (
		item_id INTEGER NOT NULL,
		phase_idx INTEGER NOT NULL,
		idx INTEGER NOT NULL,
		task TEXT NOT NULL,
		PRIMARY KEY (item_id, phase_idx, idx),
		FOREIGN KEY (item_id, phase_idx) REFERENCES plan_phases(item_id, idx)
			ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
	);

	CREATE TABLE IF NOT EXISTS item_subtasks (
		item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
		idx INTEGER NOT NULL,
		title TEXT NOT NULL,
		description TEXT,
		status TEXT NOT NULL DEFAULT 'todo',
		PRIMARY KEY (item_id, idx)
	);

	CREATE TABLE IF NOT EXISTS metadata (
		key TEXT PRIMARY KEY,
		value TEXT NOT NULL
	);

	CREATE TABLE IF NOT EXISTS feeds (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		url TEXT NOT NULL UNIQUE
	);

	CREATE TABLE IF NOT EXISTS handovers (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		origin TEXT NOT NULL,
		summary TEXT NOT NULL,
		content TEXT NOT NULL,
		created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
		recalled_at TIMESTAMPTZ
	);

	CREATE INDEX IF NOT EXISTS handovers_origin_idx ON handovers (origin);

	CREATE TABLE IF NOT EXISTS usage_peaks (
		"window" TEXT NOT NULL,
		resets_at BIGINT NOT NULL,
		segment INTEGER NOT NULL DEFAULT 0,
		used_percentage DOUBLE PRECISION NOT NULL,
		reset_detected BOOLEAN NOT NULL DEFAULT false,
		tokens_up BIGINT NOT NULL DEFAULT 0,
		tokens_down BIGINT NOT NULL DEFAULT 0,
		created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
		PRIMARY KEY ("window", resets_at, segment)
	);

	-- Backfill columns on databases created before reset/segment tracking existed.
	ALTER TABLE usage_peaks ADD COLUMN IF NOT EXISTS reset_detected BOOLEAN NOT NULL DEFAULT false;
	ALTER TABLE usage_peaks ADD COLUMN IF NOT EXISTS segment INTEGER NOT NULL DEFAULT 0;
	ALTER TABLE usage_peaks ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();
	ALTER TABLE usage_peaks ADD COLUMN IF NOT EXISTS tokens_up BIGINT NOT NULL DEFAULT 0;
	ALTER TABLE usage_peaks ADD COLUMN IF NOT EXISTS tokens_down BIGINT NOT NULL DEFAULT 0;

	-- Widen the primary key to include segment so a cycle can hold both its
	-- pre-reset peak and its post-reset continuation. Idempotent: only fires
	-- while the legacy two-column key is still in place.
	DO $$
	BEGIN
		IF EXISTS (
			SELECT 1 FROM pg_constraint
			WHERE conname = 'usage_peaks_pkey'
			  AND conrelid = 'usage_peaks'::regclass
			  AND array_length(conkey, 1) = 2
		) THEN
			ALTER TABLE usage_peaks DROP CONSTRAINT usage_peaks_pkey;
			ALTER TABLE usage_peaks ADD CONSTRAINT usage_peaks_pkey
				PRIMARY KEY ("window", resets_at, segment);
		END IF;
	END $$;

	CREATE TABLE IF NOT EXISTS backups (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
		file_path TEXT NOT NULL,
		size_bytes BIGINT NOT NULL,
		duration_ms INTEGER
	);

	-- Backfill for databases created before backup duration was tracked.
	ALTER TABLE backups ADD COLUMN IF NOT EXISTS duration_ms INTEGER;

	CREATE TABLE IF NOT EXISTS phase_usage (
		item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
		phase_idx INTEGER NOT NULL,
		tokens_up BIGINT NOT NULL DEFAULT 0,
		tokens_down BIGINT NOT NULL DEFAULT 0,
		active_ms BIGINT NOT NULL DEFAULT 0,
		peak_context_pct DOUBLE PRECISION NOT NULL DEFAULT 0,
		last_total_in BIGINT,
		last_total_out BIGINT,
		PRIMARY KEY (item_id, phase_idx)
	);

	ALTER TABLE phase_usage ADD COLUMN IF NOT EXISTS last_total_in BIGINT;
	ALTER TABLE phase_usage ADD COLUMN IF NOT EXISTS last_total_out BIGINT;
	ALTER TABLE phase_usage ADD COLUMN IF NOT EXISTS peak_context_pct DOUBLE PRECISION NOT NULL DEFAULT 0;
	ALTER TABLE phase_usage ADD COLUMN IF NOT EXISTS claude_session_id TEXT;

	CREATE TABLE IF NOT EXISTS phase_usage_messages (
		item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
		phase_idx INTEGER NOT NULL,
		message_id TEXT NOT NULL,
		PRIMARY KEY (item_id, phase_idx, message_id)
	);

	-- Git activity (branch/commit/PR) snapshotted for an item during a run. The
	-- (item_id, kind, ref) primary key makes re-snapshotting the same ref a no-op
	-- upsert rather than a duplicate row.
	CREATE TABLE IF NOT EXISTS item_git_refs (
		item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
		kind TEXT NOT NULL,
		ref TEXT NOT NULL,
		title TEXT,
		url TEXT,
		state TEXT,
		created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
		PRIMARY KEY (item_id, kind, ref)
	);
`;

export const migration0001Baseline: Migration = {
	id: 1,
	name: "baseline",
	sql,
};
