import type { Session, SessionInfo } from "./createSession";
import { repoGroupForCwd } from "./repoGroupForCwd";
import { toSessionRunInfo } from "./toSessionRunInfo";
import { joinRefusal } from "./worktree/joinRefusal";

export function toSessionInfo(session: Session): SessionInfo {
	const {
		id,
		name,
		title,
		generatedTitle,
		subtitle,
		commandType,
		harness,
		cwd,
		launchedFrom,
		claudeSessionId,
		harnessSessionId,
		restored,
		autoRun,
		autoAdvance,
		starred,
		watcher,
		design,
		verifying,
		pendingPrPreview,
		undurable,
		lastUserMessage,
		activeViewer,
		activeViewerNode,
	} = session;
	return {
		...toSessionRunInfo(session),
		id,
		name,
		title,
		generatedTitle,
		subtitle,
		commandType,
		harness,
		cwd,
		launchedFrom,
		claudeSessionId,
		harnessSessionId,
		repoGroup: repoGroupForCwd(cwd),
		restored,
		autoRun,
		autoAdvance,
		starred,
		watcher,
		design,
		verifying,
		pendingPrPreview,
		undurable,
		lastUserMessage,
		activeViewer,
		activeViewerNode,
		joinable: joinRefusal(session) === undefined,
	};
}
