import type { BacklogDb } from "./BacklogDb";

/** The backlog schema DDL. Idempotent (`IF NOT EXISTS`), so safe to run repeatedly. */
export const SCHEMA = `
	CREATE TABLE IF NOT EXISTS items (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		origin TEXT NOT NULL,
		type TEXT NOT NULL DEFAULT 'story',
		name TEXT NOT NULL,
		description TEXT,
		acceptance_criteria TEXT NOT NULL DEFAULT '[]',
		status TEXT NOT NULL DEFAULT 'todo',
		current_phase INTEGER
	);

	CREATE INDEX IF NOT EXISTS items_origin_idx ON items (origin);

	CREATE TABLE IF NOT EXISTS comments (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
		idx INTEGER NOT NULL,
		text TEXT NOT NULL,
		phase INTEGER,
		timestamp TEXT NOT NULL,
		type TEXT NOT NULL DEFAULT 'comment'
	);

	CREATE TABLE IF NOT EXISTS links (
		item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
		type TEXT NOT NULL,
		target_id INTEGER NOT NULL,
		PRIMARY KEY (item_id, type, target_id)
	);

	CREATE TABLE IF NOT EXISTS plan_phases (
		item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
		idx INTEGER NOT NULL,
		name TEXT NOT NULL,
		manual_checks TEXT,
		PRIMARY KEY (item_id, idx)
	);

	CREATE TABLE IF NOT EXISTS plan_tasks (
		item_id INTEGER NOT NULL,
		phase_idx INTEGER NOT NULL,
		idx INTEGER NOT NULL,
		task TEXT NOT NULL,
		PRIMARY KEY (item_id, phase_idx, idx),
		FOREIGN KEY (item_id, phase_idx) REFERENCES plan_phases(item_id, idx)
			ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
	);

	CREATE TABLE IF NOT EXISTS metadata (
		key TEXT PRIMARY KEY,
		value TEXT NOT NULL
	);
`;

/** Create the backlog schema if it does not already exist. Safe to call repeatedly. */
export async function ensureSchema(db: BacklogDb): Promise<void> {
	await db.exec(SCHEMA);
}
