import { PGlite } from "@electric-sql/pglite";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { ensureSchema } from "../../../shared/db/ensureSchema";
import { introspectIdentityColumns } from "./introspectIdentityColumns";

describe("introspectIdentityColumns", () => {
	let db: PGlite;

	beforeEach(async () => {
		db = new PGlite();
		await ensureSchema((sql) => db.exec(sql));
	});

	afterEach(async () => {
		await db.close();
	});

	it("discovers every identity column in the live schema", async () => {
		const columns = await introspectIdentityColumns(db);
		expect(columns).toEqual([
			{ table: "backups", column: "id", rawColumn: "id" },
			{ table: "comments", column: "id", rawColumn: "id" },
			{ table: "feeds", column: "id", rawColumn: "id" },
			{ table: "handovers", column: "id", rawColumn: "id" },
			{ table: "items", column: "id", rawColumn: "id" },
		]);
	});

	it("captures an identity column on a table created at runtime", async () => {
		await db.exec(`CREATE TABLE widgets (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			label TEXT NOT NULL
		)`);
		const columns = await introspectIdentityColumns(db);
		expect(columns).toContainEqual({
			table: "widgets",
			column: "id",
			rawColumn: "id",
		});
	});
});
