import { PGlite } from "@electric-sql/pglite";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { ensureSchema } from "../../../shared/db/ensureSchema";
import type { DumpTable } from "./DumpTable";
import { introspectDumpTables } from "./introspectDumpTables";

describe("introspectDumpTables", () => {
	let db: PGlite;
	const find = (tables: DumpTable[], name: string) =>
		tables.find((t) => t.name === name);
	const order = (tables: DumpTable[], name: string) =>
		tables.findIndex((t) => t.name === name);

	beforeEach(async () => {
		db = new PGlite();
		await ensureSchema((sql) => db.exec(sql));
	});

	afterEach(async () => {
		await db.close();
	});

	it("discovers every base table in the live schema", async () => {
		const tables = await introspectDumpTables(db);
		expect(new Set(tables.map((t) => t.name))).toEqual(
			new Set([
				"items",
				"comments",
				"links",
				"plan_phases",
				"plan_tasks",
				"metadata",
				"feeds",
				"handovers",
				"usage_peaks",
				"backups",
			]),
		);
	});

	it("returns columns in ordinal order, covering ones absent from the old constant", async () => {
		const tables = await introspectDumpTables(db);
		expect(find(tables, "items")?.columns).toEqual([
			"id",
			"origin",
			"type",
			"name",
			"description",
			"acceptance_criteria",
			"status",
			"current_phase",
			"starred",
		]);
	});

	it("quotes reserved-word identifiers so they round-trip", async () => {
		const tables = await introspectDumpTables(db);
		expect(find(tables, "usage_peaks")?.columns).toEqual([
			'"window"',
			"resets_at",
			"segment",
			"used_percentage",
			"reset_detected",
			"created_at",
		]);
	});

	it("orders tables foreign-key-safe (parents before children)", async () => {
		const tables = await introspectDumpTables(db);
		expect(order(tables, "items")).toBeLessThan(order(tables, "comments"));
		expect(order(tables, "items")).toBeLessThan(order(tables, "links"));
		expect(order(tables, "items")).toBeLessThan(order(tables, "plan_phases"));
		expect(order(tables, "plan_phases")).toBeLessThan(
			order(tables, "plan_tasks"),
		);
	});

	it("captures a table created at runtime with no source change", async () => {
		await db.exec(`CREATE TABLE widgets (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			label TEXT NOT NULL
		)`);
		const tables = await introspectDumpTables(db);
		expect(find(tables, "widgets")?.columns).toEqual(["id", "label"]);
	});
});
