import { PGlite } from "@electric-sql/pglite";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { ensureSchema } from "../../../shared/db/ensureSchema";
import { buildDump } from "./buildDump";
import type { DumpTable } from "./DumpTable";
import { introspectDumpTables } from "./introspectDumpTables";
import {
	introspectIdentityColumns,
	resyncIdentitySql,
} from "./introspectIdentityColumns";
import { parseDump } from "./parseDump";
import { validateDump } from "./validateDump";

// why: pg-copy-streams needs a real wire connection, so the test moves COPY data
// through PGlite's /dev/blob using the same COPY SQL the production copy helpers emit.
async function copyOut(db: PGlite, table: DumpTable): Promise<Buffer> {
	const { blob } = await db.query(
		`COPY ${table.name} (${table.columns.join(", ")}) TO '/dev/blob'`,
	);
	return blob ? Buffer.from(await blob.arrayBuffer()) : Buffer.alloc(0);
}

async function copyIn(
	db: PGlite,
	table: DumpTable,
	data: Buffer,
): Promise<void> {
	await db.query(
		`COPY ${table.name} (${table.columns.join(", ")}) FROM '/dev/blob'`,
		[],
		{ blob: new Blob([new Uint8Array(data)]) },
	);
}

describe("dump/restore round-trip", () => {
	let db: PGlite;

	beforeEach(async () => {
		db = new PGlite();
		await ensureSchema((sql) => db.exec(sql));
	});

	afterEach(async () => {
		await db.close();
	});

	it("captures and restores a table created at runtime, unknown to any constant", async () => {
		await db.exec(`CREATE TABLE widgets (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			label TEXT NOT NULL
		)`);
		await db.exec(
			`INSERT INTO widgets (id, label) VALUES (1, 'first'), (7, 'second')`,
		);
		await db.exec(
			`INSERT INTO usage_peaks ("window", resets_at, segment, used_percentage, reset_detected, created_at)
			 VALUES ('5h', 1000, 0, 42, false, '2026-01-01T00:00:00Z')`,
		);

		const tables = await introspectDumpTables(db);
		const dump = await buildDump(tables, (table) => copyOut(db, table));
		const parsed = parseDump(dump);
		validateDump(parsed);

		await db.exec(
			`TRUNCATE ${parsed.header.tables.map((t) => t.name).join(", ")} RESTART IDENTITY CASCADE`,
		);
		for (const table of parsed.header.tables) {
			await copyIn(
				db,
				table,
				parsed.sections.get(table.name) ?? Buffer.alloc(0),
			);
		}
		for (const col of await introspectIdentityColumns(db)) {
			const { text, values } = resyncIdentitySql(col);
			await db.query(text, values);
		}

		const widgets = await db.query("SELECT id, label FROM widgets ORDER BY id");
		expect(widgets.rows).toEqual([
			{ id: 1, label: "first" },
			{ id: 7, label: "second" },
		]);

		const reserved = await db.query('SELECT "window" FROM usage_peaks');
		expect(reserved.rows).toEqual([{ window: "5h" }]);
	});

	it("resyncs a runtime table's identity sequence past its restored rows", async () => {
		await db.exec(`CREATE TABLE widgets (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			label TEXT NOT NULL
		)`);
		await db.exec(
			`INSERT INTO widgets (id, label) VALUES (1, 'first'), (7, 'second')`,
		);

		const tables = await introspectDumpTables(db);
		const dump = await buildDump(tables, (table) => copyOut(db, table));
		const parsed = parseDump(dump);

		await db.exec(
			`TRUNCATE ${parsed.header.tables.map((t) => t.name).join(", ")} RESTART IDENTITY CASCADE`,
		);
		for (const table of parsed.header.tables) {
			await copyIn(
				db,
				table,
				parsed.sections.get(table.name) ?? Buffer.alloc(0),
			);
		}
		for (const col of await introspectIdentityColumns(db)) {
			const { text, values } = resyncIdentitySql(col);
			await db.query(text, values);
		}

		const inserted = await db.query<{ id: number }>(
			"INSERT INTO widgets (label) VALUES ('third') RETURNING id",
		);
		expect(inserted.rows).toEqual([{ id: 8 }]);
	});
});
