/** The backlog schema DDL. Idempotent (`IF NOT EXISTS`), so safe to run repeatedly. */
export const SCHEMA = `
	CREATE TABLE IF NOT EXISTS items (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		origin TEXT NOT NULL,
		type TEXT NOT NULL DEFAULT 'story',
		name TEXT NOT NULL,
		description TEXT,
		acceptance_criteria TEXT NOT NULL DEFAULT '[]',
		status TEXT NOT NULL DEFAULT 'todo',
		current_phase INTEGER,
		starred BOOLEAN NOT NULL DEFAULT false
	);

	-- Backfill the column on databases created before it was introduced.
	ALTER TABLE items ADD COLUMN IF NOT EXISTS starred BOOLEAN NOT NULL DEFAULT false;

	CREATE INDEX IF NOT EXISTS items_origin_idx ON items (origin);

	CREATE TABLE IF NOT EXISTS comments (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
		idx INTEGER NOT NULL,
		text TEXT NOT NULL,
		phase INTEGER,
		timestamp TEXT NOT NULL,
		type TEXT NOT NULL DEFAULT 'comment'
	);

	CREATE TABLE IF NOT EXISTS links (
		item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
		type TEXT NOT NULL,
		target_id INTEGER NOT NULL,
		PRIMARY KEY (item_id, type, target_id)
	);

	CREATE TABLE IF NOT EXISTS plan_phases (
		item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
		idx INTEGER NOT NULL,
		name TEXT NOT NULL,
		manual_checks TEXT,
		PRIMARY KEY (item_id, idx)
	);

	CREATE TABLE IF NOT EXISTS plan_tasks (
		item_id INTEGER NOT NULL,
		phase_idx INTEGER NOT NULL,
		idx INTEGER NOT NULL,
		task TEXT NOT NULL,
		PRIMARY KEY (item_id, phase_idx, idx),
		FOREIGN KEY (item_id, phase_idx) REFERENCES plan_phases(item_id, idx)
			ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
	);

	CREATE TABLE IF NOT EXISTS metadata (
		key TEXT PRIMARY KEY,
		value TEXT NOT NULL
	);

	CREATE TABLE IF NOT EXISTS feeds (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		url TEXT NOT NULL UNIQUE
	);

	CREATE TABLE IF NOT EXISTS handovers (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		origin TEXT NOT NULL,
		summary TEXT NOT NULL,
		content TEXT NOT NULL,
		created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
		recalled_at TIMESTAMPTZ
	);

	CREATE INDEX IF NOT EXISTS handovers_origin_idx ON handovers (origin);

	CREATE TABLE IF NOT EXISTS usage_peaks (
		"window" TEXT NOT NULL,
		resets_at BIGINT NOT NULL,
		segment INTEGER NOT NULL DEFAULT 0,
		used_percentage DOUBLE PRECISION NOT NULL,
		reset_detected BOOLEAN NOT NULL DEFAULT false,
		created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
		PRIMARY KEY ("window", resets_at, segment)
	);

	-- Backfill columns on databases created before reset/segment tracking existed.
	ALTER TABLE usage_peaks ADD COLUMN IF NOT EXISTS reset_detected BOOLEAN NOT NULL DEFAULT false;
	ALTER TABLE usage_peaks ADD COLUMN IF NOT EXISTS segment INTEGER NOT NULL DEFAULT 0;
	ALTER TABLE usage_peaks ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

	-- Widen the primary key to include segment so a cycle can hold both its
	-- pre-reset peak and its post-reset continuation. Idempotent: only fires
	-- while the legacy two-column key is still in place.
	DO $$
	BEGIN
		IF EXISTS (
			SELECT 1 FROM pg_constraint
			WHERE conname = 'usage_peaks_pkey'
			  AND conrelid = 'usage_peaks'::regclass
			  AND array_length(conkey, 1) = 2
		) THEN
			ALTER TABLE usage_peaks DROP CONSTRAINT usage_peaks_pkey;
			ALTER TABLE usage_peaks ADD CONSTRAINT usage_peaks_pkey
				PRIMARY KEY ("window", resets_at, segment);
		END IF;
	END $$;
`;

/**
 * Create the backlog schema if it does not already exist. Safe to call
 * repeatedly. The multi-statement DDL is run via `exec` — a pg pool's `query`
 * in production, PGlite's `exec` in tests — since neither Drizzle's query
 * builder nor a single parameterised query can run multiple statements at once.
 */
export async function ensureSchema(
	exec: (sql: string) => Promise<unknown>,
): Promise<void> {
	await exec(SCHEMA);
}
