const JSON_FALLBACK_LANGUAGE = "typescript";

const EXTENSION_LANGUAGE: Record<string, string> = {
	ts: "typescript",
	mts: "typescript",
	cts: "typescript",
	tsx: "typescript",
	js: "javascript",
	jsx: "javascript",
	mjs: "javascript",
	cjs: "javascript",
	json: JSON_FALLBACK_LANGUAGE,
	jsonc: JSON_FALLBACK_LANGUAGE,
	css: "css",
	scss: "scss",
	less: "less",
	py: "python",
	md: "markdown",
	markdown: "markdown",
	mdx: "mdx",
	yml: "yaml",
	yaml: "yaml",
	sh: "shell",
	bash: "shell",
	zsh: "shell",
	ps1: "powershell",
	html: "html",
	htm: "html",
	xml: "xml",
	svg: "xml",
	sql: "sql",
	rs: "rust",
	go: "go",
	java: "java",
	kt: "kotlin",
	cs: "csharp",
	rb: "ruby",
	php: "php",
	c: "cpp",
	h: "cpp",
	cpp: "cpp",
	hpp: "cpp",
	swift: "swift",
	dart: "dart",
	lua: "lua",
	r: "r",
	graphql: "graphql",
	gql: "graphql",
	dockerfile: "dockerfile",
	ini: "ini",
};

export function monacoLanguageForPath(path: string): string | undefined {
	const ext = path.split(".").pop()?.toLowerCase();
	return ext ? EXTENSION_LANGUAGE[ext] : undefined;
}
