export const deadCodeRules = new Set([
	"UnusedMember.Local",
	"UnusedType.Local",
	"UnusedParameter.Global",
	"UnusedParameter.Local",
	"NotAccessedField.Global",
	"NotAccessedField.Local",
	"NotAccessedVariable.Local",
	"UnusedAutoPropertyAccessor.Global",
	"UnusedAutoPropertyAccessor.Local",
	"ClassNeverInstantiated.Global",
	"ClassNeverInstantiated.Local",
	"UnusedMethodReturnValue.Global",
	"UnusedMethodReturnValue.Local",
	"UnusedVariable.Compiler",
	"RedundantUsingDirective",
]);
